### ISSUE TITLE
Disconnected graph results in overwrite of first ranking

### ISSUE THREAD

**Issue by michaelspiss** [kevtiq/digl#21]
Hey there - first of all thank you for this package!

From the readme I understand that digl handles disconnected graphs, but it seems like a second graph `Rank[]` overwrites the first?
For two disconnected graphs:
```
[
  {"source": "•r", "target": "0"},
  {"source": "•r", "target": "1"},
  {"source": "1", "target": "2"},
  {"source": "0", "target": "1"},
  {"source": "1", "target": "0"},
  {"source": "2", "target": "•r"},
  {"source": "3", "target": "3"},
  {"source": "4", "target": "3"},
]
```
digl returns:
```
[
  [
    ["4"],
    ["3"],
  ]
]
```

**Comment by thecrinkles** [comment]
I see what the issue is. It actually a use case that did cross my mind at one point, but i forgot about it. 

The underlying issue here is that DIGL will only see node "4" as a source node. One of the first steps is to find all source nodes of the graphs, and work from there:

- All nodes that are not a 'target' are considered a source node.
- If no nodes is found in the above, just take the first node you find (in case there is a full loop of nodes).

Your use-case falls in both categories, due to how DIGL is build, it will only look at the edges that are part of the first use check, resulting the graph you present. 

I have to look to resolve this. Which is an interesting one. I have a rough idea, but let me take closer look at it.

**Comment by michaelspiss** [comment]
Thanks for the explanation, this already helped a lot! I have fixed it for my project by simply linking to all "sources" from a root shadow node.

**Comment by thecrinkles** [comment]
With v2.0.3 (releasing at the moment) this should be solved as well. Used exactly this case in the tests (see #22 )

**Comment by michaelspiss** [comment]
Works like a charm. Thanks for your work!
